erik_prochnow_DE.wav:
  exaggeration: 1.58
  cfg_weight: 0.51
  temperature: 1.2
  repetition_penalty: 2.0
  min_p: 0.09
  top_p: 0.98
hans-juergen-lenhart_DE.wav:
  exaggeration: 1.25
  cfg_weight: 0.38
  temperature: 1.16
  repetition_penalty: 2.06
  min_p: 0.09
  top_p: 1.0
martina-zimmermann_DE.wav:
  exaggeration: 0.7
  cfg_weight: 0.49
  temperature: 1.13
  repetition_penalty: 2.1
  min_p: 0.12
  top_p: 0.98
