annie_coleman_rothenberg_1.wav::vibevoice:
  temperature: 1.2
  top_p: 0.97
  cfg_scale: 1.6
  diffusion_steps: 19.0
  voice_speed_factor: 1.0
  use_sampling: true
annie_coleman_rothenberg_1.wav::vibevoice_1_5b:
  temperature: 1.4
  top_p: 0.97
  cfg_scale: 1.4
  diffusion_steps: 20.0
  voice_speed_factor: 1.0
  use_sampling: true
annie_coleman_rothenberg_1_DE-fake_15s.wav::qwen3:
  temperature: 1.37
  top_k: 81.0
  top_p: 0.93
  subtalker_temperature: 1.43
  subtalker_top_k: 130.0
  subtalker_top_p: 0.98
  repetition_penalty: 1.05
david-barnes_DE-2-fake.wav::vibevoice:
  temperature: 1.53
  top_p: 0.95
  cfg_scale: 1.4
  diffusion_steps: 25.0
  voice_speed_factor: 1.0
  use_sampling: true
david-barnes_DE-fake.wav:
  exaggeration: 0.9
  cfg_weight: 0.2
  temperature: 1.15
  repetition_penalty: 2.5
  min_p: 0.17
  top_p: 1.0
david-barnes_DE-fake_3s.wav::vibevoice:
  temperature: 1.53
  top_p: 0.95
  cfg_scale: 1.4
  diffusion_steps: 25.0
  voice_speed_factor: 1.0
  use_sampling: true
david-barnes_DE_2_fake.wav::vibevoice:
  temperature: 1.53
  top_p: 0.95
  cfg_scale: 1.4
  diffusion_steps: 25.0
  voice_speed_factor: 1.0
  use_sampling: true
david_barnes_1_15s.wav::qwen3:
  temperature: 1.67
  top_k: 120.0
  top_p: 0.98
  subtalker_temperature: 1.48
  subtalker_top_k: 191.0
  subtalker_top_p: 0.97
  repetition_penalty: 1.06
david_barnes_2_15s.wav::qwen3:
  temperature: 1.67
  top_k: 120.0
  top_p: 0.98
  subtalker_temperature: 1.48
  subtalker_top_k: 191.0
  subtalker_top_p: 0.97
  repetition_penalty: 1.06
erik_prochnow_DE.wav:
  exaggeration: 1.58
  cfg_weight: 0.51
  temperature: 1.2
  repetition_penalty: 2.0
  min_p: 0.09
  top_p: 0.98
erik_prochnow_DE_3s.wav::qwen3:
  temperature: 1.14
  top_k: 94.0
  top_p: 1.0
  subtalker_temperature: 1.38
  subtalker_top_k: 166.0
  subtalker_top_p: 1.0
  repetition_penalty: 1.2
gesine_1.wav:
  exaggeration: 1.6
  cfg_weight: 0.2
  temperature: 1.2
  repetition_penalty: 2.02
  min_p: 0.12
  top_p: 0.94
gesine_2.wav:
  exaggeration: 0.45
  cfg_weight: 0.4
  temperature: 0.99
  repetition_penalty: 2.05
  min_p: 0.19
  top_p: 1.0
gesine_3.wav:
  exaggeration: 0.38
  cfg_weight: 0.55
  temperature: 1.03
  repetition_penalty: 2.05
  min_p: 0.15
  top_p: 1.0
hans-juergen-lenhart.wav::vibevoice:
  temperature: 1.2
  top_p: 0.97
  cfg_scale: 1.6
  diffusion_steps: 24.0
  voice_speed_factor: 1.0
  use_sampling: true
hans-juergen-lenhart_DE.wav:
  exaggeration: 1.41
  cfg_weight: 0.4
  temperature: 1.13
  repetition_penalty: 2.02
  min_p: 0.09
  top_p: 1.0
hans-juergen-lenhart_DE.wav::vibevoice:
  temperature: 1.15
  top_p: 0.97
  cfg_scale: 1.35
  diffusion_steps: 20.0
  voice_speed_factor: 1.0
  use_sampling: true
hans-juergen-lenhart_DE.wav::vibevoice_q4:
  temperature: 1.0
  top_p: 0.99
  cfg_scale: 1.4
  diffusion_steps: 40.0
  voice_speed_factor: 1.0
  use_sampling: true
hans-juergen-lenhart_DE_3s.wav::vibevoice:
  temperature: 1.15
  top_p: 0.99
  cfg_scale: 1.3
  diffusion_steps: 30.0
  voice_speed_factor: 1.0
  use_sampling: true
hans-juergen-lenhart_IT.wav::vibevoice_q4:
  temperature: 1.41
  top_p: 1.0
  cfg_scale: 1.4
  diffusion_steps: 20.0
  voice_speed_factor: 1.0
  use_sampling: true
martina-zimmermann_DE.wav:
  exaggeration: 0.7
  cfg_weight: 0.49
  temperature: 1.13
  repetition_penalty: 2.1
  min_p: 0.12
  top_p: 0.98
maryjohn_bright.wav:
  exaggeration: 1.4
  cfg_weight: 0.45
  temperature: 1.25
  repetition_penalty: 2.06
  min_p: 0.1
  top_p: 0.98
mike_kamp_2_DE.wav:
  exaggeration: 1.3
  cfg_weight: 0.25
  temperature: 1.2
  repetition_penalty: 2.0
  min_p: 0.07
  top_p: 1.0
mike_kamp_2_DE_slower.wav:
  exaggeration: 1.6
  cfg_weight: 0.22
  temperature: 1.1
  repetition_penalty: 2.0
  min_p: 0.09
  top_p: 1.0
peter_yearsley_1.wav:
  exaggeration: 0.6
  cfg_weight: 0.3
  temperature: 0.95
  repetition_penalty: 1.3
  min_p: 0.05
  top_p: 0.94
petra_ries2_DE.wav:
  exaggeration: 1.45
  cfg_weight: 0.27
  temperature: 1.05
  repetition_penalty: 2.2
  min_p: 0.09
  top_p: 0.99
petra_ries2_DE.wav::vibevoice:
  temperature: 1.3
  top_p: 0.98
  cfg_scale: 1.25
  diffusion_steps: 24.0
  voice_speed_factor: 0.96
  use_sampling: true
petra_ries2_DE_3s.wav::qwen3:
  temperature: 0.9
  top_k: 70.0
  top_p: 1.0
  subtalker_temperature: 1.15
  subtalker_top_k: 169.0
  subtalker_top_p: 1.0
  repetition_penalty: 1.0
petra_ries2_IT-Fake.wav::vibevoice:
  temperature: 0.9
  top_p: 0.98
  cfg_scale: 1.35
  diffusion_steps: 30.0
  voice_speed_factor: 0.97
  use_sampling: true
petra_ries_DE.wav:
  exaggeration: 1.45
  cfg_weight: 0.27
  temperature: 1.05
  repetition_penalty: 2.2
  min_p: 0.09
  top_p: 0.99
stefan_backes_DE.wav:
  exaggeration: 1.45
  cfg_weight: 0.19
  temperature: 0.55
  repetition_penalty: 2.1
  min_p: 0.17
  top_p: 0.96
stefan_backes_DE_kurz.wav:
  exaggeration: 1.45
  cfg_weight: 0.19
  temperature: 0.55
  repetition_penalty: 2.1
  min_p: 0.17
  top_p: 0.96
stephan_moebius_3.wav:
  exaggeration: 1.3
  cfg_weight: 0.41
  temperature: 1.3
  repetition_penalty: 2.02
  min_p: 0.07
  top_p: 1.0
ulrich_joosten_1.wav:
  exaggeration: 1.3
  cfg_weight: 0.6
  temperature: 1.3
  repetition_penalty: 1.9
  min_p: 0.1
  top_p: 0.98
ulrich_joosten_2.wav:
  exaggeration: 1.3
  cfg_weight: 0.55
  temperature: 1.25
  repetition_penalty: 2.0
  min_p: 0.12
  top_p: 0.98
ulrich_joosten_3.wav:
  exaggeration: 1.3
  cfg_weight: 0.6
  temperature: 1.3
  repetition_penalty: 1.9
  min_p: 0.1
  top_p: 0.98
