job:
  name: "Backes Reads Column"
  run-label: ""  # empty by default

input:
  reference_audio: "stefan_backes.wav"        # Filename in the reference_audio folder
  text_file: "input-document.txt"   # Text-File from the texts folder

preprocessing:
  enabled: true
  # Text normalization options
  normalize_line_endings: true    # Convert \r\n and \r to \n
  # Future preprocessing options can be added here
  # normalize_quotes: false
  # remove_extra_whitespace: false
  # fix_encoding_issues: false

chunking:
  target_chunk_limit: 480
  max_chunk_limit: 600
  min_chunk_length: 50
  spacy_model: "en_core_web_sm"

generation:
  num_candidates: 3
  max_retries: 2
  tts_params:
    # Base TTS parameters - these define the STARTING POINTS for candidate ramping:
    # - exaggeration: MAX value (ramps DOWN from here)
    # - cfg_weight: MIN value (ramps UP from here)  
    # - temperature: MIN value (ramps UP from here)
    exaggeration: 0.55                  # MAX: give maximum here
    exaggeration_max_deviation: 0.20    # Range: (ramp DOWN) [exaggeration, exaggeration-exag_max_deviation] 
    cfg_weight: 0.30                    # MIN: give minimum
    cfg_weight_max_deviation: 0.4      # Range: (ramp UP) [cfg_weight, cfg_weight+max_dev] 
    temperature: 0.5                    # MIN: give minimum
    temperature_max_deviation: 0.4      # Range: (ramp UP) [temp, temp+max_dev] 
    
  # Conservative candidate parameters for guaranteed correctness
  conservative_candidate:
    enabled: true
    exaggeration: 0.45
    cfg_weight: 0.4
    temperature: 0.7
  
validation:
  whisper_model: "small" # "base" < "small" < "medium" < "large"
  similarity_threshold: 0.85
  min_quality_score: 0.8

postprocessing:
  auto_editor:
    margin_before: 0.1
    margin_after: 0.1
    preserve_natural_sounds: true
  noise_threshold_factor: 1.5

audio:
  silence_duration:
    normal: 0.20
    paragraph: 0.80
  # ChatterboxTTS native sample rate - NOT a user setting!
  # This must match the actual output sample rate of ChatterboxTTS (24kHz)
  # Only change this if ChatterboxTTS itself changes its output sample rate
  sample_rate: 24000 