job:
  name: Backes Reads Column
  run-label: ''
input:
  text_file: input-document.txt
preprocessing:
  enabled: true
  normalize_line_endings: true
chunking:
  target_chunk_limit: 480
  max_chunk_limit: 600
  min_chunk_length: 50
  spacy_model: en_core_web_sm
generation:
  num_candidates: 1
  max_retries: 1
  speakers:
  - id: '0'
    reference_audio: stefan_backes.wav
    tts_params:
      exaggeration: 0.55
      exaggeration_max_deviation: 0.2
      cfg_weight: 0.3
      cfg_weight_max_deviation: 0.4
      temperature: 0.5
      temperature_max_deviation: 0.4
    conservative_candidate:
      enabled: true
      exaggeration: 0.45
      cfg_weight: 0.4
      temperature: 0.7
validation:
  whisper_model: small
  similarity_threshold: 0.85
  min_quality_score: 0.8
audio:
  silence_duration:
    normal: 0.2
    paragraph: 0.8
  sample_rate: 24000
