job:
  name: "default"
  run-label: ""  # empty by default

input:
  reference_audio: "mike_kamp_1.wav"        # Dateiname im reference_audio Ordner
  text_file: "input-document.txt"   # Text-Datei im texts Ordner

preprocessing:
  # Text normalization options
  enabled: true
  normalize_line_endings: true    # Convert \r\n and \r to \n
  # Future preprocessing options can be added here
  # normalize_quotes: false
  # remove_extra_whitespace: false
  # fix_encoding_issues: false

chunking:
  target_chunk_limit: 380
  max_chunk_limit: 460
  min_chunk_length: 80
  spacy_model: "en_core_web_sm"

generation:
  num_candidates: 6
  max_retries: 0
  tts_params:
    # Base TTS parameters - these define the STARTING POINTS for candidate ramping:
    # - exaggeration: MAX value (ramps DOWN from here)
    # - cfg_weight: MIN value (ramps UP from here)  
    # - temperature: MIN value (ramps UP from here)
    exaggeration: 0.40                  # MAX: give maximum here
    exaggeration_max_deviation: 0.20    # Range: (ramp DOWN) [exaggeration, exaggeration-exag_max_deviation] 
    cfg_weight: 0.2                    # MIN: give minimum
    cfg_weight_max_deviation: 0.20      # Range: (ramp UP) [cfg_weight, cfg_weight+max_dev] 
    temperature: 0.9                    # MIN: give minimum
    temperature_max_deviation: 0.3      # Range: (ramp UP) [temp, temp+max_dev] 
    repetition_penalty: 1.3             # Penalty for repeated output tokens (Chatterbox' default is 1.2) 
    
  # Conservative candidate parameters for guaranteed correctness
  conservative_candidate:
    enabled: true
    exaggeration: 0.40
    cfg_weight: 0.3
    temperature: 0.8
  
validation:
  whisper_model: "small" # "base" "small" "medium" "large"
  similarity_threshold: 0.8
  min_quality_score: 0.75

audio:
  silence_duration:
    normal: 0.40 # chunk split between sentences
    paragraph: 0.80 # chunk split between paragraphs
  # ChatterboxTTS native sample rate - NOT a user setting!
  # This must match the actual output sample rate of ChatterboxTTS (24kHz)
  # Only change this if ChatterboxTTS itself changes its output sample rate
  sample_rate: 24000 