job:
  name: "default"
  run-label: ""  # empty by default, use it to organise the tasks/files/folders

input:
  reference_audio: "mike_kamp_1.wav"  # file name in reference_audio folder
  text_file: "input-document.txt"     # file name in texts folder

preprocessing:
  enabled: true
  normalize_line_endings: true    # Convert \r\n and \r to \n
  # Future preprocessing options can be added here
  # normalize_quotes: false
  # remove_extra_whitespace: false
  # fix_encoding_issues: false

chunking:
  target_chunk_limit: 400
  max_chunk_limit: 500
  min_chunk_length: 80
  spacy_model: "en_core_web_sm"

generation:
  num_candidates: 3
  max_retries: 1
  tts_params:
    # Base TTS parameters - these define the STARTING POINTS for candidate ramping:
    # - exaggeration: MAX value (will ramp DOWN from MAX to exaggeration-exag_max_deviation)
    # - cfg_weight: MIN value (will ramp UP from MIN to cfg_weight+max_dev)  
    # - temperature: MIN value (will ramp UP from MIN to temp+max_dev)
    exaggeration: 0.55                  # give MAX here
    exaggeration_max_deviation: 0.20    # ramp DOWN 

    cfg_weight: 0.2                     # give MIN here
    cfg_weight_max_deviation: 0.40      # ramp UP 

    temperature: 0.9                    # give MIN here
    temperature_max_deviation: 0.3      # ramp UP 

    repetition_penalty: 1.3             # Penalty for repeated output tokens (Chatterbox' default is 1.2) 
    
  # Conservative candidate parameters for most likely success
  conservative_candidate:
    enabled: true
    exaggeration: 0.4
    cfg_weight: 0.5
    temperature: 0.7
  
validation:
  whisper_model: "small" # "base" "small" "medium" "large"
  similarity_threshold: 0.8
  min_quality_score: 0.75

audio:
  silence_duration:
    normal: 0.40 # chunk split between sentences
    paragraph: 0.80 # chunk split between paragraphs
  # ChatterboxTTS native sample rate - NOT a user setting!
  # This must match the actual output sample rate of ChatterboxTTS (24kHz)
  # Only change this if ChatterboxTTS itself changes its output sample rate
  sample_rate: 24000 