job:
  name: "test"
  run-label: "annie_coleman_rothenberg_1"

input:
  reference_audio: "annie_coleman_rothenberg_1.wav" # file name in reference_audio folder
  text_file: "test_short.txt" # file name in texts folder

generation:
  num_candidates: 5
  max_retries: 1 

# All other settings will be inherited from default_config.yaml