job:
  name: "example_job"
  run-label: "test_short"

input:
  text_file: "test_short.txt"  # Uses a different text file than default

generation:
  num_candidates: 1
  max_retries: 0 

# All other settings will be inherited from default_config.yaml
# This demonstrates the cascading config system 