job:
  name: pilcrowe
  run-label: 
input:
  text_file: pilcrowe.txt
preprocessing:
  enabled: true
  normalize_line_endings: false
chunking:
  target_chunk_limit: 380
  max_chunk_limit: 460
  min_chunk_length: 80
  spacy_model: en_core_web_sm
generation:
  num_candidates: 1
  max_retries: 1