job:
  name: pilcrowe
  run-label: eric_prochnow

input:
  reference_audio: cori_samuel_1.wav
  text_file: pilcrowe.txt

preprocessing:
  enabled: true
  normalize_line_endings: false    # Convert \r\n and \r to \n
  # Future preprocessing options can be added here
  # normalize_quotes: false
  # remove_extra_whitespace: false
  # fix_encoding_issues: false

chunking:
  target_chunk_limit: 380
  max_chunk_limit: 460
  min_chunk_length: 80
  spacy_model: en_core_web_sm

generation:
  num_candidates: 1
  max_retries: 1
  tts_params:
    # Base TTS parameters - these define the STARTING POINTS for candidate ramping:
    # - exaggeration: MAX value (will ramp DOWN from MAX to exaggeration-exag_max_deviation)
    # - cfg_weight: MIN value (will ramp UP from MIN to cfg_weight+max_dev)  
    # - temperature: MIN value (will ramp UP from MIN to temp+max_dev)
    exaggeration: 0.65
    exaggeration_max_deviation: 0.2 
    cfg_weight: 0.3
    cfg_weight_max_deviation: 0.3
    temperature: 1.1
    temperature_max_deviation: 0.3

  # Conservative candidate parameters for most likely success
  conservative_candidate:
    enabled: true
    exaggeration: 0.4
    cfg_weight: 0.5
    temperature: 0.7