job:
  name: pilcrowe
  run-label: eric_prochnow
input:
  text_file: pilcrowe.txt
preprocessing:
  enabled: true
  normalize_line_endings: false
chunking:
  target_chunk_limit: 380
  max_chunk_limit: 460
  min_chunk_length: 80
  spacy_model: en_core_web_sm
generation:
  num_candidates: 1
  max_retries: 1
  speakers:
  - id: '0'
    reference_audio: cori_samuel_1.wav
    tts_params:
      exaggeration: 0.65
      exaggeration_max_deviation: 0.2
      cfg_weight: 0.3
      cfg_weight_max_deviation: 0.3
      temperature: 1.1
      temperature_max_deviation: 0.3
    conservative_candidate:
      enabled: true
      exaggeration: 0.4
      cfg_weight: 0.5
      temperature: 0.7
