job:
  name: radio-broadcast
  run-label: 

input:
  text_file: radio-broadcast.txt # file name in texts folder

generation:
  num_candidates: 5
  max_retries: 1
  default_speaker: 30s-radio2
  
  # overirding some parameters for speaker peter_yearsley_1
  speakers:
    - id: 30s-radio1
      reference_audio: 30s-radio1.wav # file name in reference_audio folder
      tts_params:
        exaggeration: 0.7
        exaggeration_max_deviation: 0.3
        cfg_weight: 0.5
        cfg_weight_max_deviation: 0.2
        temperature: 0.85
        temperature_max_deviation: 0.2
        repetition_penalty: 1.5
      conservative_candidate:
        enabled: false
    - id: 30s-radio1-2
      reference_audio: 30s-radio1.wav # file name in reference_audio folder
      tts_params:
        exaggeration: 1.1
        exaggeration_max_deviation: 0.2
        cfg_weight: 0.5
        cfg_weight_max_deviation: 0.2
        temperature: 0.95
        temperature_max_deviation: 0.3
        repetition_penalty: 1.5
      conservative_candidate:
        enabled: false
    - id: 30s-radio1-3
      reference_audio: 30s-radio1.wav # file name in reference_audio folder
      tts_params:
        exaggeration: 1.3
        exaggeration_max_deviation: 0.4
        cfg_weight: 0.6
        cfg_weight_max_deviation: 0.3
        temperature: 0.95
        temperature_max_deviation: 0.3
        repetition_penalty: 1.5
      conservative_candidate:
        enabled: false
    - id: 30s-radio2
      reference_audio: 30s-radio2.wav # file name in reference_audio folder
      tts_params:
        exaggeration: 0.6
        exaggeration_max_deviation: 0.20
        cfg_weight: 0.30
        cfg_weight_max_deviation: 0.5
        temperature: 0.85
        temperature_max_deviation: 0.3
        repetition_penalty: 1.5
      conservative_candidate:
        enabled: false
    - id: 30s-radio2-2
      reference_audio: 30s-radio2.wav # file name in reference_audio folder
      tts_params:
        exaggeration: 0.7
        exaggeration_max_deviation: 0.30
        cfg_weight: 0.30
        cfg_weight_max_deviation: 0.5
        temperature: 0.95
        temperature_max_deviation: 0.3
        repetition_penalty: 1.5
      conservative_candidate:
        enabled: false

# All other settings will be inherited from default_config.yaml