job:
  name: test
  run-label: glen_hallstrom_3
input:
  text_file: test_short.txt
generation:
  num_candidates: 5
  max_retries: 1
  speakers:
  - id: '0'
    reference_audio: glen_hallstrom_3.wav
    tts_params:
      exaggeration: 0.4
      exaggeration_max_deviation: 0.25
      cfg_weight: 0.4
      cfg_weight_max_deviation: 0.25
      temperature: 0.9
      temperature_max_deviation: 0.3
      repetition_penalty: 1.2
    conservative_candidate:
      enabled: true
      exaggeration: 0.35
      cfg_weight: 0.45
      temperature: 0.7
