job:
  name: test
  run-label: stephan_moebius_3
input:
  text_file: test_short.txt
generation:
  num_candidates: 5
  max_retries: 1
  speakers:
  - id: default
    reference_audio: stephan_moebius_3.wav
    tts_params:
      exaggeration: 0.5
      exaggeration_max_deviation: 0.25
      cfg_weight: 0.15
      cfg_weight_max_deviation: 0.35
      temperature: 0.85
      temperature_max_deviation: 0.3
      repetition_penalty: 1.5
    conservative_candidate:
      enabled: true
      exaggeration: 0.4
      cfg_weight: 0.4
      temperature: 0.8
