job:
  name: "test"
  run-label: "annie_coleman_rothenberg_1"

input:
  reference_audio: "annie_coleman_rothenberg_1.wav"        # Dateiname im reference_audio Ordner
  text_file: "test_short.txt"

generation:
  num_candidates: 5
  max_retries: 0 

# All other settings will be inherited from default_config.yaml