job:
  name: test
  run-label: david_barnes_1
input:
  text_file: test_short.txt
generation:
  num_candidates: 5
  max_retries: 1
  speakers:
  - id: default
    reference_audio: david_barnes_1.wav
    tts_params:
      exaggeration: 0.5
      exaggeration_max_deviation: 0.3
      cfg_weight: 0.4
      cfg_weight_max_deviation: 0.3
      temperature: 0.95
      temperature_max_deviation: 0.2
      repetition_penalty: 1.3
    conservative_candidate:
      enabled: true
      exaggeration: 0.35
      cfg_weight: 0.6
      temperature: 0.8
