job:
  name: test
  run-label: gesine_1
input:
  text_file: test_short.txt
generation:
  num_candidates: 5
  max_retries: 1
  speakers:
  - id: '0'
    reference_audio: gesine_1.wav
    tts_params:
      exaggeration: 0.65
      exaggeration_max_deviation: 0.3
      cfg_weight: 0.2
      cfg_weight_max_deviation: 0.5
      temperature: 1.0
      temperature_max_deviation: 0.3
      repetition_penalty: 1.2
    conservative_candidate:
      enabled: true
      exaggeration: 0.5
      cfg_weight: 0.4
      temperature: 0.8
