job:
  name: test
  run-label: gesine_2
input:
  text_file: test_short.txt
generation:
  num_candidates: 5
  max_retries: 1
  audio:
  silence_duration:
    normal: 0.5
    paragraph: 0.9
  speakers:
  - id: default
    reference_audio: gesine_2.wav
    tts_params:
      exaggeration: 0.65
      exaggeration_max_deviation: 0.3
      cfg_weight: 0.3
      cfg_weight_max_deviation: 0.3
      temperature: 1.0
      temperature_max_deviation: 0.3
      repetition_penalty: 1.5
    conservative_candidate:
      enabled: true
      exaggeration: 0.5
      cfg_weight: 0.5
      temperature: 0.8
