job:
  name: voice_test
  run-label:   # empty by default, use it to organise the tasks/files/folders

input:
  text_file: voice_test.txt     # txt-file in data/input/texts folder

preprocessing:
  enabled: true
  normalize_line_endings: true    # Convert \r\n and \r to \n
  # Future preprocessing options can be added here

chunking:
  target_chunk_limit: 380
  max_chunk_limit: 460
  min_chunk_length: 80
  spacy_model: en_core_web_sm

generation:
  num_candidates: 5
  max_retries: 1
  default_speaker: test1
  
  # Speaker definitions - Define all your speakers here and reference them by id in any other job.yaml
  speakers:
    - id: test1
      reference_audio: stephan_moebius_1.wav
      tts_params:
        exaggeration: 0.52
        exaggeration_max_deviation: 0.18
        cfg_weight: 0.21
        cfg_weight_max_deviation: 0.28
        temperature: 0.95
        temperature_max_deviation: 0.26
        repetition_penalty: 1.3
        min_p: 0.045
        top_p: 0.97
      conservative_candidate:
        enabled: false
        exaggeration: 0.39
        cfg_weight: 0.45
        temperature: 0.78
        min_p: 0.08
        top_p: 0.94
    - id: test2
      tts_params:
        exaggeration: 0.3
        exaggeration_max_deviation: 0.1
        cfg_weight: 0.4
        cfg_weight_max_deviation: 0.1
        temperature: 0.95
        temperature_max_deviation: 0.20
        repetition_penalty: 1.3
        min_p: 0.05
        top_p: 0.98
    - id: test3
      tts_params:
        exaggeration: 0.65
        exaggeration_max_deviation: 0.1
        cfg_weight: 0.6
        cfg_weight_max_deviation: 0.2
        temperature: 0.95
        temperature_max_deviation: 0.20
        repetition_penalty: 1.3
        min_p: 0.05
        top_p: 0.98
    - id: test4
      tts_params:
        exaggeration: 0.7
        exaggeration_max_deviation: 0.1
        cfg_weight: 0.2
        cfg_weight_max_deviation: 0.1
        temperature: 0.95
        temperature_max_deviation: 0.20
        repetition_penalty: 1.6
        min_p: 0.045
        top_p: 0.99
