model:
  # Audio parameters
  sample_rate: 24000
  n_fft: 1024
  hop_length: 256
  win_length: 1024
  
  # Model architecture
  encoder_layers: 8
  decoder_layers: 8
  encoder_channels: [64, 128, 256, 512, 512, 512, 512, 512]
  decoder_channels: [512, 512, 512, 512, 256, 128, 64, 32]
  
  # Self-attention parameters
  attention_heads: 8
  attention_dim: 512
  attention_layers: 4
  attention_dropout: 0.1
  
  # Other parameters
  kernel_size: 3
  stride: 2
  activation: "LeakyReLU"
  normalization: "BatchNorm1d"
  crop_length: 48128  # Original training length (matches model output)

loss:
  l1_weight: 0.5          # Reduziert von 1.0 - weniger aggressiv
  stft_weight: 0.8        # Erhöht von 0.5 - mehr Frequenz-Fokus
  high_band_stft_weight: 0.2  # Reduziert von 0.3 - weniger High-Freq-Fokus
  high_band_freq_min: 6000   # Adjusted for 24kHz
  high_band_freq_max: 12000  # Nyquist frequency at 24kHz 